name: Generate Pac-Man Game on Contributions

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate Pac-Man contribution graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Rakshit05code
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#FFFF00&color_dots=#161B22,#0E4429,#006D32,#26A641,#39D353
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Pac-Man game overlay
        run: |
          mkdir -p dist
          cat > dist/pacman-game-overlay.svg << 'EOF'
          <svg width="721" height="110" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <style>
                .pacman {
                  fill: #FFFF00;
                  animation: pacman-move 8s linear infinite;
                }
                
                .ghost {
                  animation: ghost-chase 10s linear infinite;
                }
                
                .ghost-red { fill: #FF0000; }
                .ghost-pink { fill: #FFB8FF; }
                .ghost-blue { fill: #00FFFF; }
                .ghost-orange { fill: #FFB852; }
                
                .dot {
                  fill: #FFFFFF;
                  animation: dot-collect 8s linear infinite;
                }
                
                .power-pellet {
                  fill: #FFFFFF;
                  animation: power-pulse 0.8s infinite;
                }
                
                @keyframes pacman-move {
                  0% { transform: translateX(0px); }
                  25% { transform: translateX(180px); }
                  50% { transform: translateX(360px) scaleX(-1); }
                  75% { transform: translateX(180px) scaleX(-1); }
                  100% { transform: translateX(0px) scaleX(1); }
                }
                
                @keyframes ghost-chase {
                  0% { transform: translateX(0px); }
                  20% { transform: translateX(120px); }
                  40% { transform: translateX(240px); }
                  60% { transform: translateX(360px); }
                  80% { transform: translateX(240px); }
                  100% { transform: translateX(0px); }
                }
                
                @keyframes dot-collect {
                  0% { opacity: 1; }
                  12% { opacity: 1; }
                  15% { opacity: 0; }
                  100% { opacity: 0; }
                }
                
                @keyframes power-pulse {
                  0%, 100% { transform: scale(1); }
                  50% { transform: scale(1.3); }
                }
              </style>
            </defs>
            
             Pac-Man 
            <circle class="pacman" cx="40" cy="55" r="8"/>
            
             Ghosts 
            <g class="ghost ghost-red" style="transform: translate(100px, 47px);">
              <rect width="16" height="12" rx="8"/>
              <polygon points="0,12 3,16 6,12 9,16 12,12 16,16 16,8 0,8"/>
              <circle cx="4" cy="5" r="2" fill="white"/>
              <circle cx="12" cy="5" r="2" fill="white"/>
              <circle cx="4" cy="5" r="1" fill="black"/>
              <circle cx="12" cy="5" r="1" fill="black"/>
            </g>
            
            <g class="ghost ghost-pink" style="transform: translate(140px, 47px);">
              <rect width="16" height="12" rx="8"/>
              <polygon points="0,12 3,16 6,12 9,16 12,12 16,16 16,8 0,8"/>
              <circle cx="4" cy="5" r="2" fill="white"/>
              <circle cx="12" cy="5" r="2" fill="white"/>
              <circle cx="4" cy="5" r="1" fill="black"/>
              <circle cx="12" cy="5" r="1" fill="black"/>
            </g>
            
            <g class="ghost ghost-blue" style="transform: translate(180px, 47px);">
              <rect width="16" height="12" rx="8"/>
              <polygon points="0,12 3,16 6,12 9,16 12,12 16,16 16,8 0,8"/>
              <circle cx="4" cy="5" r="2" fill="white"/>
              <circle cx="12" cy="5" r="2" fill="white"/>
              <circle cx="4" cy="5" r="1" fill="black"/>
              <circle cx="12" cy="5" r="1" fill="black"/>
            </g>
            
            <g class="ghost ghost-orange" style="transform: translate(220px, 47px);">
              <rect width="16" height="12" rx="8"/>
              <polygon points="0,12 3,16 6,12 9,16 12,12 16,16 16,8 0,8"/>
              <circle cx="4" cy="5" r="2" fill="white"/>
              <circle cx="12" cy="5" r="2" fill="white"/>
              <circle cx="4" cy="5" r="1" fill="black"/>
              <circle cx="12" cy="5" r="1" fill="black"/>
            </g>
            
             Dots 
            <circle class="dot" cx="80" cy="55" r="2" style="animation-delay: 1s;"/>
            <circle class="dot" cx="120" cy="55" r="2" style="animation-delay: 1.5s;"/>
            <circle class="dot" cx="160" cy="55" r="2" style="animation-delay: 2s;"/>
            <circle class="dot" cx="200" cy="55" r="2" style="animation-delay: 2.5s;"/>
            <circle class="dot" cx="240" cy="55" r="2" style="animation-delay: 3s;"/>
            <circle class="dot" cx="280" cy="55" r="2" style="animation-delay: 3.5s;"/>
            <circle class="dot" cx="320" cy="55" r="2" style="animation-delay: 4s;"/>
            <circle class="dot" cx="360" cy="55" r="2" style="animation-delay: 4.5s;"/>
            <circle class="dot" cx="400" cy="55" r="2" style="animation-delay: 5s;"/>
            <circle class="dot" cx="440" cy="55" r="2" style="animation-delay: 5.5s;"/>
            <circle class="dot" cx="480" cy="55" r="2" style="animation-delay: 6s;"/>
            <circle class="dot" cx="520" cy="55" r="2" style="animation-delay: 6.5s;"/>
            <circle class="dot" cx="560" cy="55" r="2" style="animation-delay: 7s;"/>
            
             Power Pellets 
            <circle class="power-pellet" cx="60" cy="55" r="5"/>
            <circle class="power-pellet" cx="580" cy="55" r="5"/>
            
             Game UI 
            <text x="10" y="15" fill="#FFFF00" font-family="monospace" font-size="10" font-weight="bold">SCORE: 2840</text>
            <text x="650" y="15" fill="#FF6B6B" font-family="monospace" font-size="8">LIVES: ❤️❤️❤️</text>
            <text x="320" y="60" fill="#FFFF00" font-family="monospace" font-size="12" font-weight="bold" text-anchor="middle">READY!</text>
          </svg>
          EOF
          
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
