name: Generate Pac-Man Game Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate contribution graph base
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Rakshit05code
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=transparent&color_dots=#161B22,#0E4429,#006D32,#26A641,#39D353
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create animated Pac-Man game
        run: |
          mkdir -p dist
          cat > dist/pacman-animated-game.svg << 'EOF'
          <svg width="721" height="110" xmlns="http://www.w3.org/2000/svg" style="background: transparent;">
            <defs>
              <style>
                /* Pac-Man Animation */
                .pacman {
                  fill: #FFFF00;
                  stroke: #FFD700;
                  stroke-width: 1;
                  animation: pacman-move 12s linear infinite, pacman-chomp 0.4s infinite;
                }
                
                /* Ghost Animations */
                .ghost {
                  animation: ghost-patrol 10s linear infinite, ghost-float 1.5s ease-in-out infinite;
                }
                
                .ghost-blinky { 
                  fill: #FF0000; 
                  animation: ghost-patrol 10s linear infinite, ghost-float 1.5s ease-in-out infinite;
                  animation-delay: 0s;
                }
                
                .ghost-pinky { 
                  fill: #FFB8FF; 
                  animation: ghost-patrol 11s linear infinite, ghost-float 1.5s ease-in-out infinite;
                  animation-delay: -2s;
                }
                
                .ghost-inky { 
                  fill: #00FFFF; 
                  animation: ghost-patrol 9s linear infinite, ghost-float 1.5s ease-in-out infinite;
                  animation-delay: -4s;
                }
                
                .ghost-clyde { 
                  fill: #FFB852; 
                  animation: ghost-patrol 13s linear infinite, ghost-float 1.5s ease-in-out infinite;
                  animation-delay: -6s;
                }
                
                /* Dot Collection Animation */
                .game-dot {
                  fill: #FFFFFF;
                  animation: dot-eaten 12s linear infinite;
                }
                
                /* Power Pellet Animation */
                .power-pellet {
                  fill: #FFFFFF;
                  animation: power-pulse 0.6s infinite, power-eaten 12s linear infinite;
                }
                
                /* Maze Walls */
                .maze-wall {
                  stroke: #7289DA;
                  stroke-width: 2;
                  fill: none;
                  opacity: 0.8;
                  animation: wall-glow 3s ease-in-out infinite;
                }
                
                /* Score Popups */
                .score-text {
                  fill: #FFFF00;
                  font-family: 'Courier New', monospace;
                  font-size: 8px;
                  font-weight: bold;
                  animation: score-popup 3s ease-out infinite;
                }
                
                /* Game UI */
                .game-ui {
                  fill: #FFFFFF;
                  font-family: 'Courier New', monospace;
                  font-size: 10px;
                  font-weight: bold;
                }
                
                .ready-text {
                  fill: #FFFF00;
                  font-family: 'Courier New', monospace;
                  font-size: 14px;
                  font-weight: bold;
                  animation: ready-blink 2s infinite;
                }
                
                /* Keyframe Animations */
                @keyframes pacman-move {
                  0% { transform: translateX(0px) scaleX(1); }
                  20% { transform: translateX(140px) scaleX(1); }
                  25% { transform: translateX(160px) scaleX(1); }
                  45% { transform: translateX(300px) scaleX(1); }
                  50% { transform: translateX(320px) scaleX(-1); }
                  70% { transform: translateX(180px) scaleX(-1); }
                  75% { transform: translateX(160px) scaleX(-1); }
                  95% { transform: translateX(20px) scaleX(-1); }
                  100% { transform: translateX(0px) scaleX(1); }
                }
                
                @keyframes pacman-chomp {
                  0%, 100% { d: path("M 8,8 A 6,6 0 1,1 8,2 L 8,8 Z"); }
                  50% { d: path("M 8,8 A 6,6 0 1,1 2,8 L 8,8 Z"); }
                }
                
                @keyframes ghost-patrol {
                  0% { transform: translateX(0px); }
                  15% { transform: translateX(80px); }
                  30% { transform: translateX(160px); }
                  45% { transform: translateX(240px); }
                  60% { transform: translateX(320px); }
                  75% { transform: translateX(240px); }
                  90% { transform: translateX(120px); }
                  100% { transform: translateX(0px); }
                }
                
                @keyframes ghost-float {
                  0%, 100% { transform: translateY(0px); }
                  50% { transform: translateY(-3px); }
                }
                
                @keyframes dot-eaten {
                  0% { opacity: 1; transform: scale(1); }
                  15% { opacity: 1; transform: scale(1); }
                  18% { opacity: 0; transform: scale(0); }
                  85% { opacity: 0; transform: scale(0); }
                  88% { opacity: 1; transform: scale(1); }
                  100% { opacity: 1; transform: scale(1); }
                }
                
                @keyframes power-pulse {
                  0%, 100% { transform: scale(1); opacity: 1; }
                  50% { transform: scale(1.4); opacity: 0.6; }
                }
                
                @keyframes power-eaten {
                  0% { opacity: 1; }
                  25% { opacity: 1; }
                  30% { opacity: 0; }
                  70% { opacity: 0; }
                  75% { opacity: 1; }
                  100% { opacity: 1; }
                }
                
                @keyframes wall-glow {
                  0%, 100% { opacity: 0.8; }
                  50% { opacity: 1; }
                }
                
                @keyframes score-popup {
                  0% { opacity: 0; transform: translateY(0px) scale(0.5); }
                  15% { opacity: 1; transform: translateY(-8px) scale(1); }
                  85% { opacity: 1; transform: translateY(-12px) scale(1); }
                  100% { opacity: 0; transform: translateY(-16px) scale(0.5); }
                }
                
                @keyframes ready-blink {
                  0%, 50% { opacity: 1; }
                  51%, 100% { opacity: 0.3; }
                }
              </style>
            </defs>
            
             Maze Walls 
            <g class="maze">
              <path class="maze-wall" d="M 40,20 L 120,20 L 120,30 L 160,30 L 160,20 L 240,20"/>
              <path class="maze-wall" d="M 280,20 L 360,20 L 360,30 L 400,30 L 400,20 L 480,20"/>
              <path class="maze-wall" d="M 520,20 L 600,20 L 600,30 L 640,30 L 640,20 L 680,20"/>
              
              <path class="maze-wall" d="M 40,90 L 120,90 L 120,80 L 160,80 L 160,90 L 240,90"/>
              <path class="maze-wall" d="M 280,90 L 360,90 L 360,80 L 400,80 L 400,90 L 480,90"/>
              <path class="maze-wall" d="M 520,90 L 600,90 L 600,80 L 640,80 L 640,90 L 680,90"/>
              
              <path class="maze-wall" d="M 80,40 L 80,70"/>
              <path class="maze-wall" d="M 200,40 L 200,70"/>
              <path class="maze-wall" d="M 320,40 L 320,70"/>
              <path class="maze-wall" d="M 440,40 L 440,70"/>
              <path class="maze-wall" d="M 560,40 L 560,70"/>
            </g>
            
             Game Dots 
            <g class="dots">
              <circle class="game-dot" cx="60" cy="55" r="2" style="animation-delay: 1s;"/>
              <circle class="game-dot" cx="100" cy="55" r="2" style="animation-delay: 1.5s;"/>
              <circle class="game-dot" cx="140" cy="55" r="2" style="animation-delay: 2s;"/>
              <circle class="game-dot" cx="180" cy="55" r="2" style="animation-delay: 2.5s;"/>
              <circle class="game-dot" cx="220" cy="55" r="2" style="animation-delay: 3s;"/>
              <circle class="game-dot" cx="260" cy="55" r="2" style="animation-delay: 3.5s;"/>
              <circle class="game-dot" cx="300" cy="55" r="2" style="animation-delay: 4s;"/>
              <circle class="game-dot" cx="340" cy="55" r="2" style="animation-delay: 4.5s;"/>
              <circle class="game-dot" cx="380" cy="55" r="2" style="animation-delay: 5s;"/>
              <circle class="game-dot" cx="420" cy="55" r="2" style="animation-delay: 5.5s;"/>
              <circle class="game-dot" cx="460" cy="55" r="2" style="animation-delay: 6s;"/>
              <circle class="game-dot" cx="500" cy="55" r="2" style="animation-delay: 6.5s;"/>
              <circle class="game-dot" cx="540" cy="55" r="2" style="animation-delay: 7s;"/>
              <circle class="game-dot" cx="580" cy="55" r="2" style="animation-delay: 7.5s;"/>
              <circle class="game-dot" cx="620" cy="55" r="2" style="animation-delay: 8s;"/>
            </g>
            
             Power Pellets 
            <circle class="power-pellet" cx="30" cy="55" r="6"/>
            <circle class="power-pellet" cx="650" cy="55" r="6"/>
            
             Pac-Man 
            <g class="pacman-container">
              <circle class="pacman" cx="20" cy="55" r="8"/>
            </g>
            
             Ghosts 
            <g class="ghosts">
               Blinky (Red) 
              <g class="ghost-blinky" style="transform: translate(80px, 45px);">
                <rect width="16" height="14" rx="8" ry="8"/>
                <polygon points="0,14 2,18 4,14 6,18 8,14 10,18 12,14 14,18 16,14 16,8 0,8"/>
                <circle cx="5" cy="6" r="2" fill="white"/>
                <circle cx="11" cy="6" r="2" fill="white"/>
                <circle cx="5" cy="6" r="1" fill="black"/>
                <circle cx="11" cy="6" r="1" fill="black"/>
              </g>
              
               Pinky (Pink) 
              <g class="ghost-pinky" style="transform: translate(120px, 45px);">
                <rect width="16" height="14" rx="8" ry="8"/>
                <polygon points="0,14 2,18 4,14 6,18 8,14 10,18 12,14 14,18 16,14 16,8 0,8"/>
                <circle cx="5" cy="6" r="2" fill="white"/>
                <circle cx="11" cy="6" r="2" fill="white"/>
                <circle cx="5" cy="6" r="1" fill="black"/>
                <circle cx="11" cy="6" r="1" fill="black"/>
              </g>
              
               Inky (Cyan) 
              <g class="ghost-inky" style="transform: translate(160px, 45px);">
                <rect width="16" height="14" rx="8" ry="8"/>
                <polygon points="0,14 2,18 4,14 6,18 8,14 10,18 12,14 14,18 16,14 16,8 0,8"/>
                <circle cx="5" cy="6" r="2" fill="white"/>
                <circle cx="11" cy="6" r="2" fill="white"/>
                <circle cx="5" cy="6" r="1" fill="black"/>
                <circle cx="11" cy="6" r="1" fill="black"/>
              </g>
              
               Clyde (Orange) 
              <g class="ghost-clyde" style="transform: translate(200px, 45px);">
                <rect width="16" height="14" rx="8" ry="8"/>
                <polygon points="0,14 2,18 4,14 6,18 8,14 10,18 12,14 14,18 16,14 16,8 0,8"/>
                <circle cx="5" cy="6" r="2" fill="white"/>
                <circle cx="11" cy="6" r="2" fill="white"/>
                <circle cx="5" cy="6" r="1" fill="black"/>
                <circle cx="11" cy="6" r="1" fill="black"/>
              </g>
            </g>
            
             Score Popups 
            <text class="score-text" x="80" y="35" style="animation-delay: 1.5s;">+10</text>
            <text class="score-text" x="160" y="35" style="animation-delay: 2.5s;">+10</text>
            <text class="score-text" x="240" y="35" style="animation-delay: 3.5s;">+10</text>
            <text class="score-text" x="320" y="35" style="animation-delay: 4.5s;">+10</text>
            <text class="score-text" x="30" y="35" style="animation-delay: 2s;">+50</text>
            <text class="score-text" x="400" y="35" style="animation-delay: 6s;">+200</text>
            
             Game UI 
            <text class="game-ui" x="10" y="15" fill="#FFFF00">SCORE: 3420</text>
            <text class="game-ui" x="10" y="105" fill="#FFFFFF">LEVEL 1</text>
            <text class="game-ui" x="620" y="15" fill="#FF6B6B">LIVES: ❤️❤️❤️</text>
            <text class="ready-text" x="360" y="60" text-anchor="middle">READY!</text>
          </svg>
          EOF
          
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
