name: Generate Pac-Man Game Overlay

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate Pac-Man game on contributions
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Rakshit05code
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=#FFFF00&color_dots=#EBEDF0,#C6E48B,#7BC96F,#239A3B,#196127&snake_length=3&snake_speed=slow
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#FFFF00&color_dots=#0D1117,#0E4429,#006D32,#26A641,#39D353&snake_length=3&snake_speed=slow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Pac-Man game overlay
        run: |
          mkdir -p dist
          cat > dist/pacman-overlay.svg << 'EOF'
          <svg width="721" height="110" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <style>
                .pacman { fill: #FFFF00; animation: chomp 0.5s infinite; }
                .ghost-red { fill: #FF0000; animation: float 2s ease-in-out infinite; }
                .ghost-pink { fill: #FFB8FF; animation: float 2s ease-in-out infinite 0.5s; }
                .ghost-blue { fill: #00FFFF; animation: float 2s ease-in-out infinite 1s; }
                .ghost-orange { fill: #FFB852; animation: float 2s ease-in-out infinite 1.5s; }
                .dot { fill: #FFFFFF; animation: blink 1s infinite; }
                .power-pellet { fill: #FFFFFF; animation: pulse 0.8s infinite; }
                
                @keyframes chomp {
                  0%, 100% { d: path("M 15,15 A 10,10 0 1,1 15,5 L 15,15 Z"); }
                  50% { d: path("M 15,15 A 10,10 0 1,1 5,15 L 15,15 Z"); }
                }
                
                @keyframes float {
                  0%, 100% { transform: translateY(0px); }
                  50% { transform: translateY(-3px); }
                }
                
                @keyframes blink {
                  0%, 50% { opacity: 1; }
                  51%, 100% { opacity: 0.3; }
                }
                
                @keyframes pulse {
                  0%, 100% { transform: scale(1); opacity: 1; }
                  50% { transform: scale(1.3); opacity: 0.7; }
                }
              </style>
            </defs>
            
            <!-- Pac-Man -->
            <circle class="pacman" cx="120" cy="55" r="8"/>
            
            <!-- Ghosts -->
            <g class="ghost-red">
              <rect x="200" y="47" width="16" height="16" rx="8"/>
              <polygon points="200,63 204,67 208,63 212,67 216,63 216,55 200,55"/>
              <circle cx="204" cy="52" r="2" fill="white"/>
              <circle cx="212" cy="52" r="2" fill="white"/>
              <circle cx="204" cy="52" r="1" fill="black"/>
              <circle cx="212" cy="52" r="1" fill="black"/>
            </g>
            
            <g class="ghost-pink">
              <rect x="350" y="47" width="16" height="16" rx="8"/>
              <polygon points="350,63 354,67 358,63 362,67 366,63 366,55 350,55"/>
              <circle cx="354" cy="52" r="2" fill="white"/>
              <circle cx="362" cy="52" r="2" fill="white"/>
              <circle cx="354" cy="52" r="1" fill="black"/>
              <circle cx="362" cy="52" r="1" fill="black"/>
            </g>
            
            <g class="ghost-blue">
              <rect x="500" y="47" width="16" height="16" rx="8"/>
              <polygon points="500,63 504,67 508,63 512,67 516,63 516,55 500,55"/>
              <circle cx="504" cy="52" r="2" fill="white"/>
              <circle cx="512" cy="52" r="2" fill="white"/>
              <circle cx="504" cy="52" r="1" fill="black"/>
              <circle cx="512" cy="52" r="1" fill="black"/>
            </g>
            
            <g class="ghost-orange">
              <rect x="650" y="47" width="16" height="16" rx="8"/>
              <polygon points="650,63 654,67 658,63 662,67 666,63 666,55 650,55"/>
              <circle cx="654" cy="52" r="2" fill="white"/>
              <circle cx="662" cy="52" r="2" fill="white"/>
              <circle cx="654" cy="52" r="1" fill="black"/>
              <circle cx="662" cy="52" r="1" fill="black"/>
            </g>
            
            <!-- Dots scattered throughout -->
            <circle class="dot" cx="80" cy="30" r="1.5"/>
            <circle class="dot" cx="160" cy="25" r="1.5"/>
            <circle class="dot" cx="240" cy="35" r="1.5"/>
            <circle class="dot" cx="320" cy="30" r="1.5"/>
            <circle class="dot" cx="400" cy="25" r="1.5"/>
            <circle class="dot" cx="480" cy="35" r="1.5"/>
            <circle class="dot" cx="560" cy="30" r="1.5"/>
            <circle class="dot" cx="640" cy="25" r="1.5"/>
            
            <circle class="dot" cx="100" cy="80" r="1.5"/>
            <circle class="dot" cx="180" cy="85" r="1.5"/>
            <circle class="dot" cx="260" cy="75" r="1.5"/>
            <circle class="dot" cx="340" cy="80" r="1.5"/>
            <circle class="dot" cx="420" cy="85" r="1.5"/>
            <circle class="dot" cx="500" cy="75" r="1.5"/>
            <circle class="dot" cx="580" cy="80" r="1.5"/>
            <circle class="dot" cx="660" cy="85" r="1.5"/>
            
            <!-- Power Pellets -->
            <circle class="power-pellet" cx="50" cy="55" r="4"/>
            <circle class="power-pellet" cx="670" cy="55" r="4"/>
            
            <!-- Maze lines -->
            <path d="M 30,20 L 90,20 L 90,40 L 130,40 L 130,20 L 190,20" stroke="white" stroke-width="2" fill="none"/>
            <path d="M 230,20 L 290,20 L 290,40 L 330,40 L 330,20 L 390,20" stroke="white" stroke-width="2" fill="none"/>
            <path d="M 430,20 L 490,20 L 490,40 L 530,40 L 530,20 L 590,20" stroke="white" stroke-width="2" fill="none"/>
            
            <path d="M 30,90 L 90,90 L 90,70 L 130,70 L 130,90 L 190,90" stroke="white" stroke-width="2" fill="none"/>
            <path d="M 230,90 L 290,90 L 290,70 L 330,70 L 330,90 L 390,90" stroke="white" stroke-width="2" fill="none"/>
            <path d="M 430,90 L 490,90 L 490,70 L 530,70 L 530,90 L 590,90" stroke="white" stroke-width="2" fill="none"/>
          </svg>
          EOF
          
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
